# https://users.rust-lang.org/t/my-gitlab-config-docs-tests/16396

image: 'rust:latest'

stages:
  - test
  - doc
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y pandoc plantuml

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - cd docs && make
  only:
    - master

cache:
  paths:
    - apt/
    - cargo/
    - target/
