################################################################################
# ENVIRONTMENT
################################################################################
version: '3'

env:
  TARGET : fuzzy-pap.pdf
  DOC    : fuzzy-pap

includes:
  spap:
    taskfile: ./sa-pap-paper/Taskfile.yml
    dir: ./sa-pap-paper

################################################################################
# RECIPES
################################################################################
