# Number of processes to input values
jobs: 8

# 1: True; 0: False
plot: 1

# Time limit to solve [s]
time_limit: 100

# Output previous decision variable/param results
load_from_file: 0

# Load previous input parameters
run_prev: 0

# Verbose
verbose: 0
