# Number of processes to input values
cores: 4

# 1: True; 0: False
plot: 0

# "rand"; "csv"
schedule: "csv"

# "wait"; "rand"
solution_gen: "rand"

# Output previous decision variable/param results
load_from_file: 0

# Load previous input parameters
run_prev: 0

# Verbose
verbose: 0
