# Number of processes to input values
cores: 3

# 1: True; 0: False
plot: 0

# Real Time Plot - 1: True; 0: False
# NOTE: If this is set to 1, it is recommended to change "cores" to 1.
rtp: 0

# "rand"; "csv"
schedule: "csv"

# "wait"; "rand"
solution_gen: "wait"

# "quick"; "exhaustive"
tweak_method: "exhaustive"

# Run all constraints (slow), or run required constraints (fast)
run_all_constr: false

# Output previous decision variable/param results
load_from_file: 0

# Load previous input parameters
run_prev: 0

# Verbose
verbose: 0
