# Number of processes to input values
cores: 1

# 1: True; 0: False
plot: 0

# Real Time Plot - 1: True; 0: False
rtp: 1

# "rand"; "csv"
schedule: "csv"

# "wait"; "rand"
solution_gen: "wait"

# "quick"; "exhaustive"
tweak_method: "quick"

# Output previous decision variable/param results
load_from_file: 0

# Load previous input parameters
run_prev: 0

# Verbose
verbose: 0
