# Number of processes to input values
cores: 2

# 1: True; 0: False
plot: 0

# Real Time Plot - 1: True; 0: False
# NOTE: If this is set to 1, it is recommended to change "cores" to 1.
rtp: 0

# "linear" or "nonlinear" battery dynamic model
bat_model: "linear"

# "rand"; "csv"
schedule: "csv"

# "wait"; "rand"
solution_gen: "rand"

# "quick"; "exhaustive"
tweak_method: "exhaustive"

# Run all con
run_all_constr: false

# Output previous decision variable/param results
load_from_file: 0

# Load previous input parameters
run_prev: 0

# Verbose
verbose: 0
