time_horizon: 10.0   # [hr]
buses:
  num_bus: 25
  num_visit: 200
  bus_length: 1
  bat_capacity: 387.78 # [KWh]
  max_charge: 1        # [0-1]
  min_charge: 0.25     # [0-1]
  dis_rate: 3.0        # [Kw]
  max_rest: 0.1        # [hr]
  min_rest: 0.1        # [hr]
  max_route: 0.75      # [hr]
  min_route: 0.15      # [hr]
initial_charge:
  - 0.90               # min [0-1]
  - 0.95               # max [0-1]
final_charge: 0.95     # [0-1]
chargers:
  slow:
    num: 7
    rate: 100          # [Kw]
  fast:
    num: 4
    rate: 400          # [Kw]
