# ignore: [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58]
# ignore: [0,1,2,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58]
ignore: [27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50]
time:
  BOD: 0.0                                                                      # Beginning of day [hr]
  EOD: 24.0                                                                     # End of day [hr]
  K: 1000                                                                       # [steps]
temp:
  type: Geometric                                                               # Geometric, Exponential, Linear
  init: 9000.0                                                                  # Initial temperature
  delta: 0.999                                                                  # Temperature step size
buses:
  num_bus: 15
  num_visit: 200
  bus_length: 1
  bat_capacity: 388.0                                                           # [KWh]
  max_charge: 1                                                                 # [0-1]
  min_charge: 0.2                                                               # [0-1]
  dis_rate: 32.4                                                                # [Kw]
  max_rest: 0.3                                                                 # [hr]
  min_rest: 0.15                                                                # [hr]
initial_charge:
  max: 0.90                                                                     # [0-1]
  min: 0.90                                                                     # [0-1]
final_charge: 0.70                                                              # [0-1]
chargers:
  slow:
    num: 50
    rate: 30.0                                                                  # [Kw]
  fast:
    num: 50
    rate: 910.95                                                                # [Kw]
