name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags: 'v*.**'

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Update and Intall Dependencies
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
      - name: Setup go-task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Project
        run: task spap:clean
      - name: List Project
        run: ls -R
      - name: PlantUML
        uses: holowinski/plantuml-github-action@main
        with:
          args: -v -tpng "sa-pap-paper/sections/img/*.pml"
      - name: Build PDF
        run: task spap:images spap:pdf
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "sa-pap-paper/sa-pap.pdf LICENSE"
