name: SA PAP

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "sa-pap"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Build Project
        run: cargo build
    - name: Test Project
        run: cargo test
